version: '2'

services:
    app:
        hostname: nicehash-stats-tracker.app
        volumes:
            - ./.env:/var/www/html/.env
        build:
            context: ./
            dockerfile: docker/Dockerfile-app
        links:
            - db
        env_file:
            - .env
    db:
        hostname: nicehash-stats-tracker.db
        image: percona
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./var/mysql:/var/lib/mysql
        environment:
            TZ: Europe/London
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: nicehash_stats_tracker