#-------------------------------#
FROM composer as composer-builder
COPY . /app/
WORKDIR /app
RUN composer install --no-scripts -o -a

#-------------------------#
FROM php:7.2-fpm-alpine3.6
RUN docker-php-ext-install -j "$(getconf _NPROCESSORS_ONLN)" pdo_mysql
COPY --from=composer-builder /app /var/www/html